#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Bug routes non list√©es
controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/kernel.php
  type: annotation
  
